---
- name: Enroll monitored nodes
  hosts: controller
  gather_facts: true
  tasks:
    - name: Get list of registered Agents from Registrar
      vars:
        certs_dir: "{{ demo_dir }}/certs"
        ip: "{{ hostvars['controller']['ansible_default_ipv4']['address'] }}"
      ansible.builtin.shell:
        podman run --rm -ti -v {{ demo_dir }}/certs:/var/lib/keylime:z --network host -e KEYLIME_TENANT_REGISTRAR_IP={{ ip }} quay.io/keylime/keylime_tenant:master -c reglist
      register: registered_agents

    - name: Check if monitored nodes are registered
      vars:
        registered: "{{ registered_agents.stdout_lines[-1] | from_json | json_query('uuids') }}"
        uuid: "{{ item | to_uuid }}"
      fail:
        msg: "{{ item }} with uuid {{ uuid }} was not registered"
      when: not(uuid in registered)
      with_items: "{{ groups['monitored'] }}"

    - name: Delete agents that were enrolled before with the Verifier
      include_role:
        name: delete_agents

    - name: Enroll each monitored node using their specific policy
      vars:
        certs_dir: "{{ demo_dir }}/certs"
        local_ip: "{{ hostvars['controller']['ansible_default_ipv4']['address'] }}"
        uuid: "{{ item | to_uuid }}"
        policy: "{{ item }}.policy"
      ansible.builtin.shell:
        podman run --rm -ti -v {{ demo_dir }}/certs:/var/lib/keylime:z -v {{ demo_dir }}/policies:/var/lib/keylime/policies:z --network host -e KEYLIME_TENANT_REGISTRAR_IP={{ local_ip }} -e KEYLIME_TENANT_VERIFIER_IP={{ local_ip }} quay.io/keylime/keylime_tenant:master -c add -u {{ uuid }} --runtime-policy /var/lib/keylime/policies/{{ policy }}
      with_items: "{{ groups['monitored'] }}"

